#!/usr/bin/env bash
# install nginx server and configure it to port 80

sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx start