#!/usr/bin/env bash
# install nginx server and configure it to port 80, set the redirect_me page

apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Nimbusshub 301 Moved Permanently;/" /etc/nginx/sites-available/default
service nginx start
