#!/usr/bin/env bash
# install nginx server and configure it to port 80, set the redirect_me page

apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
var1="location /redirect_me {rewrite ^/(.*)$ https://github.com/Nimbusshub$1 permanent;}"
sed -i "30i $var1" /etc/nginx/sites-available/default
service nginx start
