#!/usr/bin/env bash
# install nginx server and configure it to port 80, set the redirect_me page

apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
var1="\\\tlocation /redirect_me {\n\t\t return 301 https://www.github.com/Nimbusshub;\n\t}\n"
sed -i "30i $var1" /etc/nginx/sites-available/default
service nginx start
