#!/usr/bin/env bash
# install nginx server and configure it to port 80, set the redirect_me page

apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
TEXT="location /redirect_me {\\n return 301 https://www.github.com/Nimbusshub;\\n}\\n"
sudo sed -i "42i $TEXT" /etc/nginx/sites-available/default
CUSTOM="error_page 404 /404.html;\nlocation = /404.html {\nroot /var/www/html;\ninternal;\n}"
sudo sed -i "/server_name _;/a $CUSTOM" /etc/nginx/sites-available/default
service nginx start